uniabuja_complaint_system/main/urls.py
from django.urls import path
from .views import index, lodge_complain

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('lodge-complain', lodge_complain, name='lodge_complain'),
]

uniabuja_complaint_system/uniabuja_complaint_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

uniabuja_complaint_system/main/models.py
from django.db import models


class Complaint(models.Model):
	name = models.CharField(max_length=100, blank=True, null=True, default='')
	complaint = models.TextField(blank=False, null=False)
	sentiment = models.CharField(verbose_name='sentiment category',
                                blank=True, null=True, max_length=20)
	date = models.DateTimeField(auto_now_add=True)

uniabuja_complaint_system/main/forms.py
from django import forms
from .models import Complaint


class ComplaintForm(forms.ModelForm):

    class Meta:
        model = Complaint
        fields = ('name', 'complaint')
        labels = {
            'name': 'Full name',
            'complaint': ' Complaint',
        }
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Enter name (or leave blank to remain anonymous)',  'class': 'form-control'}),
            'complaint': forms.Textarea(attrs={'placeholder': 'Enter complaint here', 'class': 'form-control'}),
        }

uniabuja_complaint_system/main/views.py
import os
import joblib
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import ComplaintForm
from .helper_functions import vect


cur_dir = os.path.dirname(__file__)
model = joblib.load(os.path.join(cur_dir, 'models', 'svm.joblib'))


def index(request):
	return render(request, 'main/index.html')


def lodge_complain(request):
	label = {
			-1: 'Negative',
			0: 'Neutral', 
			1:'Positive',
	}
	if request.method == 'POST':
		form = ComplaintForm(request.POST)
		if form.is_valid():
			complaint = form.save(commit=False)
			text = [complaint.complaint]
			X = vect.transform(text)
			complaint.sentiment = label[model.predict(X)[0]]
			if complaint.name == None:
				complaint.name = 'Anonymous'
			complaint.save()
			messages.success(request, 'Complaint sent successfully!')
			return redirect('main:index')
		else:
			messages.error(request, 'Error sending complaint!')
	else:
		form = ComplaintForm()
	context = {
		'form': form,
	}
	return render(request, 'main/lodge_complain.html', context)

uniabuja_complaint_system/templates/accounts/auth.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Login{% endblock %}

{% block content %}

<section class="vh-100" style="background-color: #9A616D;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-10">
        <div class="card" style="border-radius: 1rem;">
          <div class="row g-0">
            <div class="col-md-6 col-lg-5 d-none d-md-block">
              <img
                src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp"
                alt="login form"
                class="img-fluid" style="border-radius: 1rem 0 0 1rem;"
              />
            </div>
            <div class="col-md-6 col-lg-7 d-flex align-items-center">
              <div class="card-body p-4 p-lg-5 text-black">

                <form method="post">

                  <div class="d-flex align-items-center mb-3 pb-1">
                    <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                    <span class="h1 fw-bold mb-0">Login</span>
                  </div>

                  <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Sign into your account</h5>

                  <div class="form-outline mb-4">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                  </div>

                  <div class="pt-1 mb-4">
                    <button class="btn btn-dark btn-lg btn-block" type="submit">Login</button>
                  </div>

                  <a class="small text-muted" href="#!">Forgot password?</a>
                  <p class="mb-5 pb-lg-2" style="color: #393f81;">Don't have an account? <a href="{% url 'accounts:signup' %}" style="color: #393f81;">Register here</a></p>
                  <a href="#!" class="small text-muted">Terms of use.</a>
                  <a href="#!" class="small text-muted">Privacy policy</a>
                </form>


              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

uniabuja_complaint_system/templates/accounts/main.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

{% block content %}
<!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">University of Abuja <br/>e-learning Platform</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5">Education for National Unity</p>
                        <a class="btn btn-primary btn-xl" href="">Find Out More</a>
                    </div>
                </div>
            </div>
        </header>
{% endblock %}

<!--{% load pwa %}
{% progressive_web_app_meta %}
-->

uniabuja_complaint_system/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Sign up{% endblock %}

{% block content %}

<section class="vh-100" style="background-color: #9A616D;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-10">
        <div class="card" style="border-radius: 1rem;">
          <div class="row g-0">
            <div class="col-md-6 col-lg-5 d-none d-md-block">
              <img
                src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp"
                alt="login form"
                class="img-fluid" style="border-radius: 1rem 0 0 1rem;"
              />
            </div>
            <div class="col-md-6 col-lg-7 d-flex align-items-center">
              <div class="card-body p-4 p-lg-5 text-black">

                <form method="post">

                  <div class="d-flex align-items-center mb-3 pb-1">
                    <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                    <span class="h1 fw-bold mb-0">Sign up</span>
                  </div>

                  <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Sign up have an account</h5>

                  <div class="form-outline mb-4">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                  </div>

                  <div class="pt-1 mb-4">
                    <button class="btn btn-dark btn-lg btn-block" type="submit">Sign up</button>
                  </div>

                  <a href="#!" class="small text-muted">Terms of use.</a>
                  <a href="#!" class="small text-muted">Privacy policy</a>
                </form>


              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

uniabuja_complaint_system/templates/accounts/user.html
{% extends 'base.html' %}
{% block title %}Account{% endblock %}

{% block content %}
<section class="vh-100" style="background-color: #9A616D;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-10">
        <div class="card" style="border-radius: 1rem;">
          <div class="row g-0">
            <div class="col-md-6 col-lg-5 d-none d-md-block">
              <img
                src="https://www.charlton.uk.com/media/13858/studentlearning.jpg"
                alt="login form"
                class="img-fluid" style="border-radius: 1rem 0 0 1rem;"
              />
            </div>
            <div class="col-md-6 col-lg-7 d-flex align-items-center">
              <div class="card-body p-4 p-lg-5 text-black">
                  <div class="d-flex align-items-center mb-3 pb-1">
                    <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                    <span class="h1 fw-bold mb-0">Welcome to your Portal, {{ request.user.username }}</span>
                  </div>


              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

uniabuja_complaint_system/templates/accounts/verify.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Verify{% endblock %}

{% block content %}

<section class="vh-100" style="background-color: #9A616D;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-10">
        <div class="card" style="border-radius: 1rem;">
          <div class="row g-0">
            <div class="col-md-6 col-lg-5 d-none d-md-block">
              <img
                src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp"
                alt="login form"
                class="img-fluid" style="border-radius: 1rem 0 0 1rem;"
              />
            </div>
            <div class="col-md-6 col-lg-7 d-flex align-items-center">
              <div class="card-body p-4 p-lg-5 text-black">

                <form method="post">

                  <div class="d-flex align-items-center mb-3 pb-1">
                    <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                    <span class="h1 fw-bold mb-0">Token</span>
                  </div>

                  <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Enter 6 digit code sent to phone.</h5>

                  <div class="form-outline mb-4">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                  </div>

                  <div class="pt-1 mb-4">
                    <button class="btn btn-dark btn-lg btn-block" type="submit">Verify</button>
                  </div>


                </form>


              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

uniabuja_complaint_system/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}Uniabuja{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
            <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link rel="icon" type="image/png" href="{% static 'images/icon.png' %}">

    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'main:index' %}">Uniabuja</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="">Welcome, {{ user.username|title }}</a></li>
                            <li class="nav-item"><a class="nav-link" href="">Courses</a></li>
                            <li class="nav-item"><a class="nav-link" href="">Logout</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link" href="">Login</a></li>
                            <li class="nav-item"><a class="nav-link" href="">Sign up</a></li>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link" href="">Contact</a></li>
                        <li class="nav-item"><a class="nav-link" target="_blank" href="{% url 'admin:index'%}">Admin only</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock %}

        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright &copy; 2023 - Uniabuja</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- SimpleLightbox plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

uniabuja_complaint_system/templates/main/auth.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Login{% endblock %}

{% block content %}

<section class="vh-100" style="background-color: #9A616D;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-10">
        <div class="card" style="border-radius: 1rem;">
          <div class="row g-0">
            <div class="col-md-6 col-lg-5 d-none d-md-block">
              <img
                src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp"
                alt="login form"
                class="img-fluid" style="border-radius: 1rem 0 0 1rem;"
              />
            </div>
            <div class="col-md-6 col-lg-7 d-flex align-items-center">
              <div class="card-body p-4 p-lg-5 text-black">

                <form method="post">

                  <div class="d-flex align-items-center mb-3 pb-1">
                    <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                    <span class="h1 fw-bold mb-0">Login</span>
                  </div>

                  <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Sign into your account</h5>

                  <div class="form-outline mb-4">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                  </div>

                  <div class="pt-1 mb-4">
                    <button class="btn btn-dark btn-lg btn-block" type="submit">Login</button>
                  </div>

                  <a class="small text-muted" href="#!">Forgot password?</a>
                  <p class="mb-5 pb-lg-2" style="color: #393f81;">Don't have an account? <a href="{% url 'accounts:signup' %}" style="color: #393f81;">Register here</a></p>
                  <a href="#!" class="small text-muted">Terms of use.</a>
                  <a href="#!" class="small text-muted">Privacy policy</a>
                </form>


              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

uniabuja_complaint_system/templates/main/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

{% block content %}
<!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <center class='text-white'>
                            <!-- for all messages -->
                            {% if messages %}
                              {% for message in messages %}
                                <span class="alert {{ message.tags }} alert-dismissible shadow fade show col-lg-6" role="alert">
                                    {{ message|safe }}
                                </span>
                              {% endfor %}
                            {% endif %}
                        </center>
                        <h1 class="text-white font-weight-bold">University of Abuja <br/>Complaint System</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5">Education for National Unity</p>
                        <a class="btn btn-primary btn-xl" href="{% url 'main:lodge_complain' %}">Lodge a complain</a>
                    </div>
                </div>
            </div>
        </header>
<script>
setTimeout(() => {
    const alerts = document.querySelectorAll(".alert");
    alerts.forEach(alert => {
        alert.style.display = 'none';
    });
}, 5000);
</script>        
{% endblock %}

uniabuja_complaint_system/templates/main/lodge_complain.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block title %}Lodge a Complain{% endblock %}

{% block content %}

<section class="vh-100" style="background-color: #9A616D;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-10">
        <div class="card" style="border-radius: 1rem;">
          <div class="row g-0">
            <div class="col-md-6 col-lg-5 d-none d-md-block">
              <img
                src="{% static 'images/student.png' %}"
                alt="login form"
                class="img-fluid" style="border-radius: 1rem 0 0 1rem;"
              />
            </div>
            <div class="col-md-6 col-lg-7 d-flex align-items-center">
              <div class="card-body p-4 p-lg-5 text-black">

                <form method="post">

                  <div class="d-flex align-items-center mb-3 pb-1">
                    <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                    <span class="h1 fw-bold mb-0">Lodge your complain</span>
                  </div>

                  <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Your complaints are confidential</h5>
                  <center class='text-white'>
                    <!-- for all messages -->
                    {% if messages %}
                      {% for message in messages %}
                        <span class="alert {{ message.tags }} alert-dismissible shadow fade show col-lg-6" role="alert">
                            {{ message|safe }}
                        </span>
                      {% endfor %}
                    {% endif %}
                  </center>

                  <div class="form-outline mb-4">
                      {% csrf_token %}
                      {% bootstrap_form form %}
                  </div>
                  <!-- <div class="form-group">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                  </div>                   -->

                  <div class="pt-1 mb-4">
                    <button class="btn btn-dark btn-lg btn-block" type="submit">Submit</button>
                  </div>

                </form>


              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<script>
setTimeout(() => {
    const alerts = document.querySelectorAll(".alert");
    alerts.forEach(alert => {
        alert.style.display = 'none';
    });
}, 5000);
</script>
{% endblock %}

uniabuja_complaint_system/templates/main/user.html
{% extends 'base.html' %}
{% block title %}Account{% endblock %}

{% block content %}
<section class="vh-100" style="background-color: #9A616D;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-10">
        <div class="card" style="border-radius: 1rem;">
          <div class="row g-0">
            <div class="col-md-6 col-lg-5 d-none d-md-block">
              <img
                src="https://www.charlton.uk.com/media/13858/studentlearning.jpg"
                alt="login form"
                class="img-fluid" style="border-radius: 1rem 0 0 1rem;"
              />
            </div>
            <div class="col-md-6 col-lg-7 d-flex align-items-center">
              <div class="card-body p-4 p-lg-5 text-black">
                  <div class="d-flex align-items-center mb-3 pb-1">
                    <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                    <span class="h1 fw-bold mb-0">Welcome to your Portal, {{ request.user.username }}</span>
                  </div>


              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

uniabuja_complaint_system/templates/main/verify.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Verify{% endblock %}

{% block content %}

<section class="vh-100" style="background-color: #9A616D;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-xl-10">
        <div class="card" style="border-radius: 1rem;">
          <div class="row g-0">
            <div class="col-md-6 col-lg-5 d-none d-md-block">
              <img
                src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp"
                alt="login form"
                class="img-fluid" style="border-radius: 1rem 0 0 1rem;"
              />
            </div>
            <div class="col-md-6 col-lg-7 d-flex align-items-center">
              <div class="card-body p-4 p-lg-5 text-black">

                <form method="post">

                  <div class="d-flex align-items-center mb-3 pb-1">
                    <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                    <span class="h1 fw-bold mb-0">Token</span>
                  </div>

                  <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Enter 6 digit code sent to phone.</h5>

                  <div class="form-outline mb-4">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                  </div>

                  <div class="pt-1 mb-4">
                    <button class="btn btn-dark btn-lg btn-block" type="submit">Verify</button>
                  </div>


                </form>


              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}